### ISSUE TITLE
Feature request: add section for ads

### ISSUE THREAD

**Issue by mrfanatic** [ItsAnubhav/WorDroid-Plugin#1]
Hi @ItsAnubhav will it be possible to **add a section** where we can insert custom ads in an HTML textarea, which will then be displayed on the app home screen?

**Comment by ItsAnubhav** [comment]
Adsense ads use JavaScript. So you can only show it inside of a post (WebView).

**Comment by mrfanatic** [comment]
Ah right, i didn't think about that. Maybe a custom local advertisement using the WordPress media uploader? Display only image ads.

**Comment by ItsAnubhav** [comment]
Yes. Image Banner is possible.
